---
title: "Rworksheet#4a_camayodo"
author: "Ann Margaret A. Camayodo"
date: "2023-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1.
HouseholdData <-data.frame(
Shoesize = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
Height = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
)
HouseholdData
View(HouseholdData)
#A. The data is a dataframe called "HouseholdData" with three variables: "Shoesize", "Height", and "Gender".

----------------------------------------------------------------------
#B.
Male <- subset(HouseholdData, Gender == "M")
Male
#Output
#MaleData
#   Shoesize Height Gender
#14     10.5   71.0      M
#15     13.0   77.0      M
#16     11.5   72.0      M
#19     10.0   72.0      M
#22      8.5   67.0      M
#23     10.5   73.0      M
#25     10.5   72.0      M
#26     11.0   70.0      M
#27      9.0   69.0      M
#28     13.0   70.0      M
Female <- subset(HouseholdData, Gender == "F")
Female
#Output
# Shoesize Height Gender
#1       6.5   66.0      F
#2       9.0   68.0      F
#3       8.5   64.5      F
#4       8.5   65.0      F
#6       7.0   64.0      F
#7       9.5   70.0      F
#8       9.0   71.0      F
#10      7.5   64.0      F
#12      8.5   67.0      F
#17      8.5   59.0      F
#18      5.0   62.0      F
#20      6.5   66.0      F
#21      7.5   64.0      F
#24      8.5   69.0      F

----------------------------------------------------------------------
#C.
mean_shoe <- mean(HouseholdData$Shoesize)
cat("Mean shoe size:", mean_shoe)
#Output: 
#Mean shoe size: 9.410714

mean_height <- mean(HouseholdData$Height)
cat("Mean height:", mean_height)
#Output:
#Mean height: 68.57143

----------------------------------------------------------------------
#D.
#Most People who has a shoe size of 10 and above are tall people so it has some relationship between shoe size and height

----------------------------------------------------------------------

#2.
Months <- c("March","April","January","November","January", "September","October","September","November","August", "January","November","November","February","May","August", "July","December","August","August","September","November","February", "April")

Factor_Months_Vector <- factor(Months)
Factor_Months_Vector

----------------------------------------------------------------------

#3. 
#Theyre both useful 
summary(Months)
summary(Factor_Months_Vector)

----------------------------------------------------------------------

#4.
DirVector <- rep(c("East", "West", "North"), times = c(1, 4, 3))
new_order_data <- factor(DirVector, levels = c("East", "West", "North"))
new_order_data

----------------------------------------------------------------------

#5.
